# .streamlit/secrets.toml
# Configuración para la nube

ENTORNO = "produccion"
DB_HOST = "localhost"
DB_PORT = 5432
DB_NAME = "postgres"
DB_USER = "postgres"
DB_PASSWORD = "mi_password"
OLLAMA_URL = "http://localhost:11434"
OLLAMA_MODEL = "llama3.1:8b"
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
EMAIL_USER = "samupor527@gmail.com"
EMAIL_PASSWORD = "tybu wutf cadd vqxm"
MODO_AUTOMATICO = true
MODO_DIOS = true